
ALTER TABLE tracks MODIFY COLUMN audio_file VARCHAR(1024);
ALTER TABLE tracks MODIFY COLUMN audio_clip VARCHAR(1024);
ALTER TABLE tracks MODIFY COLUMN ipl_file VARCHAR(1024);
ALTER TABLE releases MODIFY COLUMN cover_art VARCHAR(1024);
